sudo: true
language: node_js

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
os:
  - linux

node_js:
  - "6"
  - "4"

matrix:
  allow_failures:
    - node_js: "4"

script: cd $TRAVIS_BUILD_DIR/plugins/zlib && npm test && cd $TRAVIS_BUILD_DIR/plugins/zopfli && npm test

env:
  - CXX=g++-4.8

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8

install: 
  - npm install yarn -g
  - cd $TRAVIS_BUILD_DIR/plugins/zlib && yarn install
  - cd $TRAVIS_BUILD_DIR/plugins/zopfli && yarn install
